name: Deploy Cloud Composer DAGs

on:
  workflow_dispatch

jobs:
  deploy-dags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }} 

      - name: Trigger Cloud Build for DAG deployment
        uses: google-github-actions/cloudbuild-build@v1
        with:
          project_id: ardent-case-465107-c9
          build_config_path: add-dags-to-composer.cloudbuild.yaml
