name: Deploy Cloud Composer DAGs

on:
  workflow_dispatch

jobs:
  deploy-dags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }} 

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Trigger Cloud Build
        run: |
          gcloud builds submit --project=ardent-case-465107-c9 . --config=add-dags-to-composer.cloudbuild.yaml
